# configs/base_config.yaml
# RUN WITH: uv run python -m src.mlopsproject.train
# or without wandb: python -m src.mlopsproject.train wandb.enabled=false

wandb:
  enabled: false
  project: MLOps_jacob
  entity: mlops12
  group: faces_${epochs}
  mode: online

seed: 42

# trainer
epochs: 1
lr: 4e-4
device: auto
save_model: True
batch_size: 64

# checkpoint saving and loading
#checkpoint_name: "faces_epochs${epochs}_lr${lr}_model.pt"

# GCS configuration for cross-platform data & model storage
gcs:
  project: "active-premise-484209-h0"
  bucket: "data-face-emotions"
  data_folder: "data_train"
  model_folder: "models"
  use_mounted_path: false          

hydra:
  run:
    dir: outputs/single/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: train_faces
