# configs/base_config.yaml
# RUN WITH: uv run python -m src.mlopsproject.train
# or without wandb: python -m src.mlopsproject.train wandb.enabled=false
wandb:
  enabled: true          # turn off with wandb.enabled=false
  project: MLOps_signe # CHANGE THIS BEFORE RUNNING
  entity: mlops12    # <- W&B team slug
  group: faces_${epochs}   # group runs by bottleneck type
  mode: online           # or "offline" / "disabled"

seed: 42

# trainer
epochs: 1
lr: 4e-4
device: auto            # "cuda" | "cpu" | "auto"
save_model: True

# checkpoint saving and loading
checkpoint_name: "faces_epochs${epochs}_lr${lr}_model.pt"

hydra:
  run:
    dir: outputs/single/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: train_faces
